spring:
  application:
    name: config-service
  cloud:
    config:
        server:
            git:
                uri: https://github.com/EazyGoTravel/EGT_CONFIGURATION.git
                default-label: main   
server:
    port: 9696

    
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    preferIpAddress: true