spring:
  cloud:
    config:
        server:
            git:
                uri: https://github.com/Neeharkakulla/EGT_CONFIGURATION.git
                default-label: main 
  application:
    name: config-service
       
server:
    port: 9696
    
eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/
  instance:
    hostname: localhost
    preferIpAddress: false